language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

dist: trusty

git:
  depth: 5

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    
cache:
  - composer
  - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - export PATH="./vendor/bin:$PATH"
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - phpcs --standard=phpcs.xml $(find . -name '*.php')
  - phpmd src text ./phpmd.xml

after_success:
 - bash <(curl -s https://codecov.io/bash)
 